In [82]:
import pandas as pd

In [83]:
datos =  pd.read_csv('Datos/IMDB Dataset SPANISH.csv', index_col=0) #cargar el dataset y eliminar la columna de índices
datos = datos[["review_es", "sentimiento"]].copy() #seleccionar solo las columnas de texto y etiqueta
datos.columns = ["texto", "etiqueta"] #renombrar las columnas para mayor claridad
datos.head() #mostrarlas

                                               texto  etiqueta
0  Uno de los otros críticos ha mencionado que de...  positivo
1  Una pequeña pequeña producción.La técnica de f...  positivo
2  Pensé que esta era una manera maravillosa de p...  positivo
3  Básicamente, hay una familia donde un niño peq...  negativo
4  El "amor en el tiempo" de Petter Mattei es una...  positivo

In [84]:
datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   texto     50000 non-null  str
 1   etiqueta  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

In [85]:
datos.value_counts("etiqueta")

etiqueta
positivo    25000
negativo    25000
Name: count, dtype: int64

In [86]:
datos.isnull().sum()

texto       0
etiqueta    0
dtype: int64

In [87]:
datos.duplicated().sum()

np.int64(401)

In [88]:
#Eliminar datos duplicados
datos = datos.drop_duplicates()
datos.duplicated().sum()

np.int64(0)

In [89]:
#mapear las etiquetas a valores numéricos (1 para positivo, 0 para negativo)
datos["etiqueta"] = datos["etiqueta"].map({"positivo": 1, "negativo": 0}) 
datos.head() #mostrar las primeras filas para verificar el cambio

                                               texto  etiqueta
0  Uno de los otros críticos ha mencionado que de...         1
1  Una pequeña pequeña producción.La técnica de f...         1
2  Pensé que esta era una manera maravillosa de p...         1
3  Básicamente, hay una familia donde un niño peq...         0
4  El "amor en el tiempo" de Petter Mattei es una...         1

In [90]:
datos = datos[datos["texto"].str.strip() != ""]# eliminar filas con texto vacío
datos.duplicated().sum()
datos.head()

                                               texto  etiqueta
0  Uno de los otros críticos ha mencionado que de...         1
1  Una pequeña pequeña producción.La técnica de f...         1
2  Pensé que esta era una manera maravillosa de p...         1
3  Básicamente, hay una familia donde un niño peq...         0
4  El "amor en el tiempo" de Petter Mattei es una...         1

In [91]:
datos.info()

<class 'pandas.DataFrame'>
Index: 49599 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   texto     49599 non-null  str
 1   etiqueta  49599 non-null  int64
dtypes: int64(1), str(1)
memory usage: 1.1 MB